Feat/main panel
pop123123123/web-sm-client pull request #2
Opened 2021-07-01 15:06 UTC by caimez323

2021-07-01 17:57 UTC, pop123123123 requested changes

2021-07-01 17:57 UTC, pop123123123 commented on src/components/Menu.vue
> +      items: [
commands

2021-07-01 17:57 UTC, pop123123123 commented on src/components/Menu.vue
> +        { command: 'Undo', shortcuts: 'Ctrl+z' },
enlever le "s"

2021-07-01 17:57 UTC, pop123123123 commented on src/components/Menu.vue
> +      this.$store.dispatch('MENU_ACTION', name);
Dispatch plutôt le name directement comme, avec les commandes étant des actions existantes

2021-07-01 17:57 UTC, pop123123123 commented on src/store/index.js
> +    combos: [{ sentence: 'Bonjour', comboIndex: 2 }],
Enlever ce test

2021-07-01 17:57 UTC, pop123123123 commented on src/router/index.js
> +    name: 'Panel',
Trouver un meilleur nom

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +  <div class="table">
Pourquoi class="table" ?

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        newElement = { element, index };
Fusionner les lignes

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      :items-per-page="12"
Forcer une seule page

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +              :rules="[max25chars]"
Pourquoi ?

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      if (!(n === -1 && this.$store.state.combos[index].comboIndex === 0)) {
`if (this.$store.state.combos[index].comboIndex + n >= 0)`

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +    increaseComboIndex(index, n) {
`changeComboIndex(row, n)`

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +          > -->
À supprimer ?

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      filteredSearch: this.$store.state.combos,
```suggestion
      filteredLines: this.$store.state.combos,
```

2021-07-01 17:57 UTC, pop123123123 commented on src/store/index.js
> +    combos: [{ sentence: 'Bonjour', comboIndex: 2 }],
combos => segments

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      max25chars: (v) => v.length <= 25 || 'Input too long!',
C'est bien, mais pourquoi ?

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      left: '<',
Utiliser &lt; et &gt; directement dans le html

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        { text: 'Index', value: 'element.comboIndex' },
Aligner les comboIndex à droite et rendre la colonne la plus étroite possible

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      this.$store.dispatch('NEW_EMPTY_SENTENCE');
On ne fera jamais ça (création multiple de segments vides)

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      });
créer une action qui s'occupe de la suppression multiple
De plus, cet algorithme ne fonctionne qu'avec les sélections contiguës

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +    remove() {
```suggestion
    deleteSelected() {
```

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      }
Faire un switch

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      this.clipboard.forEach((element) => this.$store.dispatch('NEW_SENTENCE', { sentence: element.element.sentence, comboIndex: element.element.comboIndex }));
Créer une action de création multiple de segments non-vides

2021-07-01 17:57 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      this.$store.dispatch('MENU_ACTION', '');
Transformer ces actions en action Vuex, rajouter la sélection dans le store, enlever le `MENU_ACTION` et dispatch les actions dans `menu` et `paneltable`
Actions : Commencer à créer une "hiérarchie" des actions, par exemple séparer les actions `commands`, etc...
State : faire un objet correspondant aux propriétés en bijection avec l'état du serveur, les autres propriétés étant propres au client

2021-07-01 17:57 UTC, pop123123123 commented on src/store/index.js
> +    menuAction: '',
À enlever

2021-07-01 17:57 UTC, pop123123123 commented on src/store/index.js
> +    NEW_EMPTY_SENTENCE(state, position) {
transformer position en un index, et créer une seule mutation qui ajoute un segment à un index spécifique

2021-07-01 17:57 UTC, pop123123123 commented on src/store/index.js
> +    },
À supprimer

2021-07-01 17:57 UTC, pop123123123 commented on src/store/index.js
>    actions: {
créer des actionTypes, séparées comme décrit plus haut

2021-07-01 17:57 UTC, pop123123123 commented on src/views/Panel.vue
> +<Menu name="Action" />
Indentation ?

2021-07-01 17:57 UTC, pop123123123 commented on src/views/Panel.vue
> +      >
Faudrait être sûr de bien utiliser le linting d'eslint, là c'est pas très beau

2021-07-01 17:57 UTC, pop123123123 commented on src/views/Panel.vue
> +      <ProjectPopUp v-if="showPopup" @closed="showPopup = false"></ProjectPopUp>
Pas besoin de deux projectpopup

2021-07-01 17:57 UTC, pop123123123 commented on src/views/Panel.vue
> +        </md-card-header>
```suggestion
        <md-card-header>
          <div class="md-title">{{ $store.state.project.name }}</div>
          <div class="md-subhead">Seed: {{ $store.state.project.seed }}</div>
        </md-card-header>
```

2021-07-01 17:57 UTC, pop123123123 commented on src/views/Panel.vue
> +        </md-card-header>
Pas besoin de titre, sinon tu peux mettre "Preview"

2021-07-01 17:57 UTC, pop123123123 commented on src/views/Panel.vue
> +}
```suggestion
```

2021-07-02 07:42 UTC, caimez323 commented on src/components/PanelTable.vue
> +              :rules="[max25chars]"
De base c'était pour inciter l'utilisateur à pas faire de phrase trop longue

2021-07-02 11:20 UTC, pop123123123 commented on src/components/PanelTable.vue
> +              :rules="[max25chars]"
J'aime bien l'idée, mais j'ai l'impression que ça va plus nous embêter qu'autre chose, faudrait plutôt mettre un warning ou autre, qui te montre que c'est pas recommandé mais qui te laisse faire si tu as vraiment envie

2021-07-05 13:07 UTC, pop123123123 requested changes

2021-07-05 13:07 UTC, pop123123123 commented on src/components/Menu.vue
> +      ],
Mettre directement les noms d'action, pour éviter d'avoir à faire le switch (veiller à bien utiliser action-types)

2021-07-05 13:07 UTC, pop123123123 commented on src/components/Menu.vue
> +      }
Pas besoin du switch si les noms des commandes sont des noms d'actions

2021-07-05 13:07 UTC, pop123123123 commented on src/store/action-types.js
> +    DELETE_SELECTED: 'DELETE_SELECTED',
Préfixe les chaînes par `COMMAND_` pour qu'on puisse facilement les identifier pendant le débogage

2021-07-05 13:07 UTC, pop123123123 commented on src/store/index.js
> +    },
Remove devrait pouvoir prendre une liste d'indices

2021-07-05 13:07 UTC, pop123123123 commented on src/store/index.js
> +    },
Pas besoin de s'embêter avec des sommes, on peut juste passer le nouvel index et le remplacer

2021-07-05 13:07 UTC, pop123123123 commented on src/store/index.js
> +    },
Redondantes

2021-07-05 13:07 UTC, pop123123123 commented on src/store/index.js
> +    },
Redondantes, et après ça te complique la vie vu que tu dois faire des `if (....length == 1)`

2021-07-05 13:07 UTC, pop123123123 commented on src/store/index.js
> +        state.dispatch('NEW_SENTENCE', {
Partout : utiliser `state.commit(mutation.MA_MUTATION)` et `state.dispatch(action.MON_ACTION)` au lieu des chaînes en dur

2021-07-05 13:07 UTC, pop123123123 commented on src/views/Panel.vue
> +            <div class="md-subhead">Seed:{{ $store.state.project.seed }}</div>
Indentation

2021-07-05 13:07 UTC, pop123123123 commented on src/views/Panel.vue
> +  },
Fermer

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      :single-select="false"
Est déjà à false par défaut

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +               :rules="[max25chars]"
indentation

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        @click="$store.dispatch('NEW_EMPTY_SENTENCE', lines.length)"
Utiliser `action.***`

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +          $store.dispatch('DELETE_SELECTED');
Utiliser `action.***`

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        v-if="$store.state.selected.length > 0"
Plutôt directement lier le booléen à `disabled`
```suggestion
        :disabled="$store.state.selected.length === 0"
```

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +          selected = [];
Ce serait logique que l'action s'en charge

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +            this.$store.dispatch('DELETE_SELECTED');
Utiliser `action.***`, je te laisse chercher partout où tu l'as fait dans le projet, pour les actions et les mutations

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +          this.selected = [];
À faire dans l'action

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        this.$store.commit('CHANGE_COMBO_INDEX', { row, n });
Faire le calcul du nouvel index ici

2021-07-05 13:07 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      });
```suggestion
      return this.$store.state.segments.map((element, index) => ({element, index }));
```

2021-07-05 14:30 UTC, caimez323 commented on src/components/PanelTable.vue
> +          selected = [];
la c'est l'action du composant donc je peux la modifier qu'ici non ?

2021-07-06 08:18 UTC, pop123123123 requested changes

2021-07-06 08:18 UTC, pop123123123 commented on src/components/Menu.vue
> +      ],
Utiliser actions

2021-07-06 08:18 UTC, pop123123123 commented on src/components/Menu.vue
> +      if (command === 'COMMAND_ADD') {
Utiliser actions

2021-07-06 08:18 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        this.$store.commit(mutation.CHANGE_INDEX_COMBO, {
Faire une action command plutôt, à terme ça passera par le serveur

2021-07-06 14:29 UTC, pop123123123 requested changes

2021-07-06 14:29 UTC, pop123123123 commented on src/components/Menu.vue
> +      ],
Du coup il faut toujours utiliser `action` !

2021-07-06 14:29 UTC, pop123123123 commented on src/store/action-types.js
> +    TRY_CHANGE_SENTENCE: 'TRY_CHANGE_SENTENCE',
Pourquoi ce nom ?

2021-07-06 14:29 UTC, pop123123123 commented on src/store/index.js
> +      state.commit(mutation.CHANGE_SENTENCE, { index: item.index, newSentence: editSentence });
Changer les paramètres comme suit (et les endroits qui utilisent l'action
```suggestion
    [action.command.TRY_CHANGE_SENTENCE](state, { index, newSentence: }) {
      state.commit(mutation.CHANGE_SENTENCE, { index, newSentence });
```

2021-07-06 14:29 UTC, pop123123123 commented on src/components/PanelTable.vue
> +            this.selected = [];
Pareil que juste en-dessous

2021-07-06 14:29 UTC, pop123123123 commented on src/components/PanelTable.vue
> +          selected = [];
Faire la liaison de la sélection du store à la sélection dans ce composant

2021-07-07 21:43 UTC, pop123123123 requested changes

2021-07-07 21:43 UTC, pop123123123 commented on src/store/action-types.js
> +    CHANGE_SENTENCE: 'CHANGE_SENTENCE',
```suggestion
    CHANGE_COMBO_INDEX: 'COMMAND_CHANGE_COMBO_INDEX',
    CHANGE_SENTENCE: 'COMMAND_CHANGE_SENTENCE',
```

2021-07-07 21:43 UTC, pop123123123 commented on src/store/mutation-types.js
> +  CHANGE_MENU_ACTION: 'CHANGE_MENU_ACTION',
Plus besoin si ?

2021-07-07 21:43 UTC, pop123123123 commented on src/store/mutation-types.js
> +  PUSH_INDEX_EMPTY_SENTENCE: 'PUSH_INDEX_EMPTY_SENTENCE',
Redondant

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +    menuAction: '',
Plus utile

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +    },
```suggestion
    [mutation.PUSH_EMPTY_SENTENCE](state) {
      state.segments.splice(index ?? state.segments.length, 0, { sentence: '', comboIndex: 0 });
    },
```

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +    },
À supprimer

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +      state.commit(mutation.PUSH_INDEX_EMPTY_SENTENCE, realIndex);
```suggestion
    [action.command.NEW_EMPTY_SENTENCE]({ state, commit }, index) {
      const realIndex = index ?? state.segments.length;
      commit(mutation.PUSH_INDEX_EMPTY_SENTENCE, realIndex);
```

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +    [action.CREATE_PROJECT](state, newProject) {
Dans toutes les actions tu as mis `state` comme nom au premier argument, mais il s'agit du `context`
Soit tu remplaces partout par `context`, soit tu déstructures `[action.CREATE_PROJECT]({ commit }, newProject) {` pour y prendre seulement ce qui t'intéresse

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +      });
```suggestion
      state.state.selected.forEach((id, index) => {
        state.commit(mutation.REMOVE, id - index);
      });
```

cf [la doc de forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +      state.segments.splice(index, 1);
Ajouter de quoi mettre éventuellement la sélection à jour (diminuer les indices ou supprimer l'élément éventuel)

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +      state.segments.push({ sentence, comboIndex });
Ajouter une logique de mise à jour de la sélection (offset éventuel de certains indices)

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +      state.segments.push({ sentence: '', comboIndex: 0 });
Même chose

2021-07-07 21:43 UTC, pop123123123 commented on src/store/index.js
> +      state.commit(mutation.RESET_SELECTED);
Sera déjà fait par les mutations (cf plus haut)

2021-07-07 21:43 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      return highlighted;
```suggestion
      return this.$store.state.selected.map((element) => this.lines[element]);
```

2021-07-07 21:43 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      }
```suggestion
      const mode = sel.value ? 'add' : 'remove';
      this.$store.dispatch(
        action.CHANGE_SELECTION,
        { newIndex: sel.item.index, mode },
      );
```

2021-07-07 21:43 UTC, pop123123123 commented on src/components/PanelTable.vue
> +      }
```suggestion
      const mode = sel.value ? 'add' : 'remove';
      all.items.forEach((item) => this.$store.dispatch(
        action.CHANGE_SELECTION, { newIndex: item.index, mode },
      ));
```

2021-07-09 07:25 UTC, pop123123123 requested changes

2021-07-09 07:25 UTC, pop123123123 commented on src/components/PanelTable.vue
> +        this.$store.commit(action.command.CHANGE_COMBO_INDEX, {
```suggestion
        this.$store.dispatch(action.command.CHANGE_COMBO_INDEX, {
```

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +  if (state.selected.length > 0) {
Inutile

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +function selectionOffset(state, targetIndex, modeAdd) {
```suggestion
function offsetSelection(state, targetIndex, modeAdd) {
```
`selectionOffset` ← décalage de la sélection / offset est un nom commun (variable)
`offsetSelection` ← décale  la sélection / offset est un verbe (fonction)

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +    [action.command.NEW_SENTENCE](context, indexList) {
`DUPLICATE_SENTENCE` ?

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +          },
```suggestion
          element: {...context.state.segments[index]},
```
En soi tu pourrais faire `element: context.state.segments[index},`, mais tu aurais des soucis car les deux seraient une référence vers le même objet (si tu en modifies l'un, l’autre est modifié aussi)

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +      });
Cet algo ne marche pas (exemple : `selected = [4,2,0]`, il va supprimer 4, puis 1, puis -2).
Le plus simple serait de supprimer dans l'ordre décroissant des indices.
Donc soit garder selected toujours trié (pas très dur), soit le trier avant la suppression.

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +      selectionOffset(state, index, 0);
Il faudrait aussi supprimer l'élément supprimé de selected s'il est présent

2021-07-09 07:25 UTC, pop123123123 commented on src/store/index.js
> +      commit(mutation.RESET_SELECTED);
Plus besoin après les modifs de `DELETE`

2021-07-09 11:49 UTC, pop123123123 requested changes

2021-07-09 11:49 UTC, pop123123123 commented on src/components/PanelTable.vue
> +    {{ $store.state.selected }}
À supprimer

2021-07-09 11:58 UTC, pop123123123 approved these changes

2021-07-09 11:58 UTC, merged